///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class DImages {
  DImages._();

  static const String assetsBg = 'assets/bg_bottom.png';
  static const String assetsBgTop = 'assets/bg_top.png';
  static const String assetsIcIcon = 'assets/ic_icon.jpg';

}
